UPDATE WAREHOUSE SET W_YTD = W_YTD + 2431.1  WHERE W_ID = 1
SELECT W_STREET_1, W_STREET_2, W_CITY, W_STATE, W_ZIP, W_NAME FROM WAREHOUSE WHERE W_ID = 1
UPDATE DISTRICT SET D_YTD = D_YTD + 2431.1 WHERE D_W_ID = 1 AND D_ID = 9
SELECT D_STREET_1, D_STREET_2, D_CITY, D_STATE, D_ZIP, D_NAME FROM DISTRICT WHERE D_W_ID = 1 AND D_ID = 9
SELECT C_FIRST, C_MIDDLE, C_ID, C_STREET_1, C_STREET_2, C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM, C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE FROM CUSTOMER WHERE C_W_ID = 1 AND C_D_ID = 9 AND C_LAST = 'PRESPRESANTI' ORDER BY C_FIRST
UPDATE CUSTOMER SET C_BALANCE = -2441.1, C_YTD_PAYMENT = 2441.1, C_PAYMENT_CNT = 2 WHERE C_W_ID = 1 AND C_D_ID = 9 AND C_ID = 447
INSERT INTO HISTORY (H_C_D_ID, H_C_W_ID, H_C_ID, H_D_ID, H_W_ID, H_DATE, H_AMOUNT, H_DATA)  VALUES (9,1,447,9,1,'2015-09-25 13:17:47',2431.1,'sxvnj    fllkmrwx')
SELECT D_NEXT_O_ID, D_TAX FROM DISTRICT WHERE D_W_ID = 1 AND D_ID = 5 FOR UPDATE
UPDATE DISTRICT SET D_NEXT_O_ID = D_NEXT_O_ID + 1 WHERE D_W_ID = 1 AND D_ID = 5
INSERT INTO OORDER (O_ID, O_D_ID, O_W_ID, O_C_ID, O_ENTRY_D, O_OL_CNT, O_ALL_LOCAL) VALUES (3144, 5, 1, 1795, '2015-09-25 13:17:47', 13, 1)
INSERT INTO NEW_ORDER (NO_O_ID, NO_D_ID, NO_W_ID) VALUES ( 3144, 5, 1)
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 48870
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 48870 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 28373
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 28373 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 52945
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 52945 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 98023
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 98023 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 47195
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 47195 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 95921
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 95921 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 79847
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 79847 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 61062
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 61062 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 81639
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 81639 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 32211
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 32211 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 9546
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 9546 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 91735
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 91735 AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA FROM ITEM WHERE I_ID = 14886
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10 FROM STOCK WHERE S_I_ID = 14886 AND S_W_ID = 1 FOR UPDATE
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,1,48870,1,6,456.18,'cueuhlztbgbbknsqrpgjnnc')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,2,28373,1,2,21.98,'xjsfnygmjukunznayffumxo')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,3,52945,1,5,129.15,'xvkrysnrgzjrzgdbivgjphp')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,4,98023,1,2,123.48,'qrcvrkgpwjsoirfdiykvasi')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,5,47195,1,3,237.75,'kqrqibpwsnpsezktfuvhjfm')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,6,95921,1,4,171.8,'uofkqrmuxkoyzemssadaxbz')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,7,79847,1,3,248.61002,'hnxuxewyaqespkraynigdzt')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,8,61062,1,8,601.6,'kpivvyluujdnmgclqwgxvwr')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,9,81639,1,5,44.6,'ztfditfwwbgxcwtpquxqyep')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,10,32211,1,7,643.86005,'igmiqgvrpfbqrdncdqukhog')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,11,9546,1,10,742.0,'gqqwxxtuwlwwekpxxomnoag')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,12,91735,1,10,773.2,'xlhwffxipkbcyyluagxtvus')
INSERT INTO ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_I_ID, OL_SUPPLY_W_ID,  OL_QUANTITY, OL_AMOUNT, OL_DIST_INFO) VALUES (3144,5,1,13,14886,1,6,226.13998,'dwnlsddqymuxvdexwdknhpd')
UPDATE STOCK SET S_QUANTITY = 23 , S_YTD = S_YTD + 6, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 48870 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 72 , S_YTD = S_YTD + 2, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 28373 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 54 , S_YTD = S_YTD + 5, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 52945 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 92 , S_YTD = S_YTD + 2, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 98023 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 59 , S_YTD = S_YTD + 3, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 47195 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 32 , S_YTD = S_YTD + 4, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 95921 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 57 , S_YTD = S_YTD + 3, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 79847 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 59 , S_YTD = S_YTD + 8, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 61062 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 93 , S_YTD = S_YTD + 5, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 81639 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 24 , S_YTD = S_YTD + 7, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 32211 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 81 , S_YTD = S_YTD + 10, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 9546 AND S_W_ID = 1
UPDATE STOCK SET S_QUANTITY = 34 , S_YTD = S_YTD + 10, S_ORDER_CNT = S_ORDER_CNT + 1, S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 91735 AND S_W_ID = 1
SELECT C_FIRST, C_MIDDLE, C_ID, C_STREET_1, C_STREET_2, C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM, C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE FROM CUSTOMER WHERE C_W_ID = 2 AND C_D_ID = 8 AND C_LAST = 'PRESCALLYATION' ORDER BY C_FIRST
SELECT O_ID, O_CARRIER_ID, O_ENTRY_D FROM OORDER WHERE O_W_ID = 2 AND O_D_ID = 8 AND O_C_ID = 479 ORDER BY O_ID DESC LIMIT 1
SELECT OL_I_ID, OL_SUPPLY_W_ID, OL_QUANTITY, OL_AMOUNT, OL_DELIVERY_D FROM ORDER_LINE WHERE OL_O_ID = 1232 AND OL_D_ID =8 AND OL_W_ID = 2
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 1 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 1 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 1 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 1 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 1 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 1 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 59339.14, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 1 AND C_ID = 326
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 2 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 2 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 2 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 2 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 2 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 2 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 31414.21, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 2 AND C_ID = 2784
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 3 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 3 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 3 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 3 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 3 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 3 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 69291.82, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 3 AND C_ID = 71
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 4 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 4 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 4 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 4 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 4 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 4 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 60594.46, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 4 AND C_ID = 2659
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 5 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 5 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 5 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 5 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 5 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 5 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 50296.09, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 5 AND C_ID = 2170
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 6 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 6 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 6 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 6 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 6 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 6 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 70138.54, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 6 AND C_ID = 1192
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 7 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 7 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 7 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 7 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 7 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 7 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 24289.66, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 7 AND C_ID = 2241
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 8 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 8 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 8 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 8 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 8 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 8 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 33183.96, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 8 AND C_ID = 1428
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 9 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 9 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 9 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 9 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 9 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 9 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 15883.86, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 9 AND C_ID = 235
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 10 AND NO_W_ID = 1 ORDER BY NO_O_ID ASC LIMIT 1
DELETE FROM NEW_ORDER WHERE NO_O_ID = 2274 AND NO_D_ID = 10 AND NO_W_ID = 1
SELECT O_C_ID FROM OORDER WHERE O_ID = 2274 AND O_D_ID = 10 AND O_W_ID = 1
UPDATE OORDER SET O_CARRIER_ID = 2 WHERE O_ID = 2274 AND O_D_ID = 10 AND O_W_ID = 1
UPDATE ORDER_LINE SET OL_DELIVERY_D = '2015-09-25 13:17:47' WHERE OL_O_ID = 2274 AND OL_D_ID = 10 AND OL_W_ID = 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM ORDER_LINE WHERE OL_O_ID = 2274 AND OL_D_ID = 10 AND OL_W_ID = 1
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE + 68081.49, C_DELIVERY_CNT = C_DELIVERY_CNT + 1 WHERE C_W_ID = 1 AND C_D_ID = 10 AND C_ID = 2545
SELECT D_NEXT_O_ID FROM DISTRICT WHERE D_W_ID = 1 AND D_ID = 9
SELECT COUNT(DISTINCT (S_I_ID)) AS STOCK_COUNT FROM ORDER_LINE, STOCK WHERE OL_W_ID = 1 AND OL_D_ID = 9 AND OL_O_ID < 3182 AND OL_O_ID >= 3182 - 20 AND S_W_ID = 1 AND S_I_ID = OL_I_ID AND S_QUANTITY < 14
